name: "ad_reporting"
version: "1.0.1"
config-version: 2

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  ad_reporting:
    +materialized: table
    +schema: ad_reporting
    intermediate:
      +materialized: ephemeral
      +schema: int_ad_reporting

  facebook_ads_source:
    +schema: attract_facebook_ads

vars:
  facebook_ads_schema: attract_facebook_ads
  facebook_ads_database: raw
  ad_reporting__facebook_ads_enabled: True # by default this is assumed to be True
  ad_reporting__apple_search_ads_enabled: False # by default this is assumed to be True
  ad_reporting__pinterest_ads_enabled: False # by default this is assumed to be True
  ad_reporting__microsoft_ads_enabled: False # by default this is assumed to be True
  ad_reporting__linkedin_ads_enabled: False # by default this is assumed to be True
  ad_reporting__google_ads_enabled: False # by default this is assumed to be True
  ad_reporting__twitter_ads_enabled: False # by default this is assumed to be True
  ad_reporting__snapchat_ads_enabled: False # by default this is assumed to be True
  ad_reporting__tiktok_ads_enabled: False # by default this is assumed to be True
